---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: apachedeployment
spec:
 replicas: 2
 strategy: 
    type: Recreate
 selector: 
   matchLabels: 
     app: apacheapp
 template:
  metadata:
   name: apachepod
   labels:
     app: apacheapp	 
  spec: 
    containers:
    - name: apachecontainer
      image: rama90/apacheapp
      imagePullPolicy: Always
      ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
 name: apachesvc
spec:
  type: NodePort
  selector:
   app: apacheapp
  ports:
   - port: 80
     targetPort: 8080
     nodePort: 30007
...
